--liquibase formatted sql
--changeset vladikshk:create_initial_tables

create table Author (
                        id int generated by default as identity primary key,
                        name varchar(100) not null
);

create table Book (
                      id int generated by default as identity primary key ,
                      name varchar(100) not null ,
                      author_id int references Author(id) on delete set null
);

create table Tag (
                     id int generated by default as identity primary key,
                     name varchar(100) not null
);

create table book_tag (
                          book_id int references Book(id) on delete cascade,
                          tag_id int references Tag(id) on delete cascade,
                          primary key (book_id, tag_id)
);
